import {Inter} from "next/font/google";
import Script from 'next/script'
import "@/styles/globals.css";
import "@/styles/common.css";
import {ReduxProvider} from "@/src/store";
import {ConfigProvider} from 'antd';
import zhCN from 'antd/es/locale/zh_CN'; // 引入中文语言包

const inter = Inter({subsets: ["latin"]});

export const metadata = {
    title: "Baosteel",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <head>
            <Script src="/static/js/echarts.js" strategy={"beforeInteractive"}></Script>
        </head>
        <body className={inter.className}>
        <ConfigProvider locale={zhCN}>
            <ReduxProvider>
                {children}
            </ReduxProvider>
        </ConfigProvider>
        </body>
        </html>
    );
}
