import {Inter} from "next/font/google";
import "@/styles/globals.css";
import "@/styles/common.css";

const inter = Inter({subsets: ["latin"]});

export const metadata = {
    title: "探风",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className={inter.className}>
        {children}
        </body>
        </html>
    );
}
