import {Inter} from "next/font/google";
import Script from 'next/script'
import "@/styles/globals.css";
import "@/styles/common.css";
import {ReduxProvider} from "@/src/store";
import {ConfigProvider} from 'antd';
import zhCN from 'antd/locale/zh_CN'; // 引入中文语言包
import dayjs from 'dayjs';
import 'dayjs/locale/zh-cn';
import 'moment/dist/locale/zh-cn.js';

dayjs.locale('zh-cn');

const inter = Inter({subsets: ["latin"]});

export const metadata = {
    title: "Baosteel",
    description: "Generated by create next app. Version - 14.2.5",
};

export default function RootLayout({children}) {
    return (
        <html lang="zh">
        <head>
            <Script src="/static/js/echarts.js" strategy={"beforeInteractive"}></Script>
            <Script src="/static/js/echarts-wordcloud.js" strategy={"beforeInteractive"}></Script>
        </head>
        <body className={inter.className}>
        <ConfigProvider locale={zhCN}>
            <ReduxProvider>
                {children}
            </ReduxProvider>
        </ConfigProvider>
        </body>
        </html>
    );
}
