
POST http://127.0.0.1:2999/wmappserver/topview/getAllGroups
Content-Type: application/json

{}

###




POST http://127.0.0.1:2999/wmappserver/topview/getLabelNames
Content-Type: application/json

{
}

###



POST http://127.0.0.1:2999/wmappserver/topview/getGroupAvgScore
Content-Type: application/json

{
  "groupId": 1001,
  "month": "2025-01"
}

###




POST http://127.0.0.1:2999/wmappserver/topview/getClassesByGroupId
Content-Type: application/json

{
  "groupId": 1001
}

###


POST http://127.0.0.1:2999/wmappserver/topview/getClassAvgScoreInMonth
Content-Type: application/json

{
  "classIdList": [
    2001,
    2002,
    2003
  ],
  "month": "2025-01"
}

###


POST http://127.0.0.1:2999/wmappserver/topview/getChartData1
Content-Type: application/json

{
  "classIdList": [
    2001,
    2002,
    2003
  ],
  "month": "2025-01"
}

###


POST http://127.0.0.1:2999/wmappserver/topview/getChartData2
Content-Type: application/json

{
  "classIdList": [
    2001,
    2002,
    2003
  ],
  "startMonth": "2025-01",
  "length": 10
}

###


POST http://127.0.0.1:2999/wmappserver/topview/getChartData3
Content-Type: application/json

{
  "groupId": 1003,
  "month": "2025-01"
}

###