
POST http://127.0.0.1:2999/wmappserver/topview/getAllGroups
Content-Type: application/json

{}

###




POST http://127.0.0.1:2999/wmappserver/topview/getLabelNames
Content-Type: application/json

{
}

###



POST http://127.0.0.1:2999/wmappserver/topview/getGroupAvgScore
Content-Type: application/json

{
  "groupId": 1001,
  "month": "2025-01"
}

###




POST http://127.0.0.1:2999/wmappserver/topview/getClassesByGroupId
Content-Type: application/json

{
  "groupId": 1001
}

###